=== aonsolutions/aon-application/aon-report/src/main/resources/com/code/aon/report/config/report-config.dtd
<?xml encoding="UTF-8"?>

<!ELEMENT report-config (default-config?,report+)>
<!ELEMENT default-config (fetch-mode?,params?)>
<!ELEMENT report (template,((bean,criteria,fetch-mode?)|collection)?,params?,nested-report*,dynamic-params?)>
<!ELEMENT template EMPTY>
<!ELEMENT bean EMPTY>
<!ELEMENT criteria EMPTY>
<!ELEMENT nested-report EMPTY>
<!ELEMENT fetch-mode EMPTY>
<!ELEMENT collection EMPTY>
<!ELEMENT params (param)+>
<!ELEMENT param EMPTY>
<!ELEMENT dynamic-params EMPTY>


<!ATTLIST report-config xmlns CDATA #FIXED ''>
<!ATTLIST default-config xmlns CDATA #FIXED ''>
<!ATTLIST report xmlns CDATA #FIXED ''
  description CDATA #REQUIRED
  id NMTOKEN #REQUIRED>
<!ATTLIST template xmlns CDATA #FIXED ''
  path CDATA #REQUIRED>
<!ATTLIST bean xmlns CDATA #FIXED ''
  key CDATA #REQUIRED>
<!ATTLIST criteria xmlns CDATA #FIXED ''
  provider CDATA #REQUIRED>
<!ATTLIST collection xmlns CDATA #FIXED ''
  provider CDATA #REQUIRED>
<!ATTLIST nested-report xmlns CDATA #FIXED ''
  report NMTOKEN #REQUIRED>
<!ATTLIST fetch-mode xmlns CDATA #FIXED ''
  paginated CDATA #REQUIRED
  page-count CDATA #IMPLIED
  virtualizer-max-size CDATA #IMPLIED>
<!ATTLIST params
  xmlns CDATA #FIXED ''>
<!ATTLIST param
  xmlns CDATA #FIXED ''
  id CDATA #REQUIRED
  value CDATA #REQUIRED>
<!ATTLIST dynamic-params xmlns CDATA #FIXED ''
  provider CDATA #REQUIRED>

=== aonsolutions/aon-application/tags/v_4_2_0/aon-ui-purchase/src/main/resources/META-INF/report-config.xml
<?xml version="1.0" encoding="ISO-8859-1"?>

<!DOCTYPE report-config 
	PUBLIC "-//CODE-AON//DTD Report Config//EN" 
	"http://co-de.com/aon/report-config.dtd">

<report-config>
	
	<!--  *********  Listado Detallado Pedido de Compras  ********* -->

	<report id="purchaseList" description="Listado de purchase">
		<template path="/com/code/aon/ui/purchase/report/purchaseList.jasper" />
		<bean key="com.code.aon.purchase.Purchase" />
		<criteria provider="#{purchase}"/>
		<params>
			<param id="REPORT_RESOURCE_BUNDLE" value="com.code.aon.ui.purchase.i18n.report" />
			<param id="company" value="#{company.obtainCompany}" />
			<param id="logoImageFile" value="#{company.getAttachAsInputStream}" />
			<param id="recordData" value="#{company.getCompanyRecordData}" />
			<param id="phone" value="#{company.obtainPhone}" />
			<param id="fax" value="#{company.obtainFax}" />
			<param id="email" value="#{company.obtainEmail}" />
			<param id="web" value="#{company.obtainWeb}" />
			<param id="address" value="#{company.obtainAddress}" />
			<param id="printRecordData" value="#{company.isPrintRecordData}"/>
			<param id="printHeader" value="#{company.isPrintHeader}" />
			<param id="PriceStrategy" value="#{purchaseDetail.getPriceStrategy}" />
			<param id="TotalPrice" value="#{purchase.getTotalPrice}" />
			<param id="defaultPayMethod" value="#{purchase.getDefaultPayMethod}" />
		</params>
	</report>

	<report id="purchaseDetailledList" description="Listado Detallado de purchase">
		<template path="/com/code/aon/ui/purchase/report/purchaseDetailledList.jasper" />
		<bean key="com.code.aon.purchase.Purchase" />
		<criteria provider="#{purchase}"/>
		<params>
			<param id="REPORT_RESOURCE_BUNDLE" value="com.code.aon.ui.purchase.i18n.report" />
			<param id="company" value="#{company.obtainCompany}" />
			<param id="logoImageFile" value="#{company.getAttachAsInputStream}" />
			<param id="recordData" value="#{company.getCompanyRecordData}" />
			<param id="phone" value="#{company.obtainPhone}" />
			<param id="fax" value="#{company.obtainFax}" />
			<param id="email" value="#{company.obtainEmail}" />
			<param id="web" value="#{company.obtainWeb}" />
			<param id="address" value="#{company.obtainAddress}" />
			<param id="printRecordData" value="#{company.isPrintRecordData}"/>
			<param id="printHeader" value="#{company.isPrintHeader}" />
			<param id="PriceStrategy" value="#{purchaseDetail.getPriceStrategy}" />
			<param id="TotalPrice" value="#{purchase.getTotalPrice}" />
			<param id="defaultPayMethod" value="#{purchase.getDefaultPayMethod}" />
		</params>
		<nested-report report="purchaseListDetail"/>
		<nested-report report="purchaseListTaxBreakDown"/>
	</report>
	
	<report id="purchaseListDetail" description="purchase Details">
		<template path="/com/code/aon/ui/purchase/report/purchaseListDetail.jasper" />
	</report>
	<report id="purchaseListTaxBreakDown" description="taxBreakDown">
		<template path="/com/code/aon/ui/purchase/report/purchaseListTaxBreakDown.jasper"/>
	</report>
</report-config>

=== aonsolutions/aon-application/aon-ui-accounting/src/main/resources/META-INF/report-config.xml
<?xml version="1.0" encoding="ISO-8859-1"?>

<!DOCTYPE report-config 
	PUBLIC "-//CODE-AON//DTD Report Config//EN" 
	"http://co-de.com/aon/report-config.dtd">

<report-config>

	<!--  **********************************************************
						      ACCOUNTING
		  ********************************************************** -->
	<!--  BALANCE DE PERDIDAS Y GANACIAS -->
	<report id="profitAndLoss" description="ProfitAndLoss">
		<template path="/com/code/aon/ui/accounting/report/profitAndLoss.jasper"/>
		<collection provider="#{profitAndLossReport}"/>
		<params>
			<param id="REPORT_RESOURCE_BUNDLE" value="com.code.aon.ui.accounting.i18n.report" />
			<param id="company" value="#{company.obtainCompany}" />
			<param id="params" value="#{profitAndLossReport.getParameters}" />
			<param id="reportTitle" value="#{profitAndLossReport.getReportTitle}" />
		</params>
	</report>

	<!--  BALANCE MESUAL DE PERDIDAS Y GANACIAS -->
	<report id="profitAndLossMonthly" description="ProfitAndLossMonthly">
		<template path="/com/code/aon/ui/accounting/report/profitAndLossMonthly.jasper"/>
		<collection provider="#{profitAndLossMonthly}"/>
		<params>
			<param id="REPORT_RESOURCE_BUNDLE" value="com.code.aon.ui.accounting.i18n.report" />
			<param id="company" value="#{company.obtainCompany}" />
			<param id="params" value="#{profitAndLossReport.getParameters}" />
		</params>
	</report>

	<!--  BALANCE DE PERDIDAS Y GANACIAS PRESUPUESTADO -->
	<report id="budgetedProfitAndLoss" description="BudgetedProfitAndLoss">
		<template path="/com/code/aon/ui/accounting/report/profitAndLoss.jasper"/>
		<collection provider="#{budgetedProfitAndLossReport}"/>
		<params>
			<param id="REPORT_RESOURCE_BUNDLE" value="com.code.aon.ui.accounting.i18n.report" />
			<param id="company" value="#{company.obtainCompany}" />
			<param id="params" value="#{budgetedProfitAndLossReport.getParameters}" />
			<param id="reportTitle" value="#{budgetedProfitAndLossReport.getReportTitle}" />
		</params>
	</report>
	
	<!--  LISTADO DE CUENTAS CON PRESUPUESTO -->
	<report id="budgetList" description="BudgetList">
		<template path="/com/code/aon/ui/accounting/report/budgetList.jasper"/>
		<bean key="com.code.aon.accounting.AccountBudget" />
		<criteria provider="#{accountBudget}"/>
		<fetch-mode paginated="true" page-count="5000" virtualizer-max-size="1000" />
		<params>
			<param id="REPORT_RESOURCE_BUNDLE" value="com.code.aon.ui.accounting.i18n.report" />
			<param id="company" value="#{company.obtainCompany}" />
			<param id="creditTotal" value="#{accountBudget.getCreditTotal}" />
			<param id="debitTotal" value="#{accountBudget.getDebitTotal}" />
		</params>
	</report>
	
	<!--  BALANCE DE PERDIDAS Y GANACIAS PRESUPUESTADO -->
	<report id="profitAndLossComparison" description="BudgetedProfitAndLoss">
		<template path="/com/code/aon/ui/accounting/report/profitAndLossComparison.jasper"/>
		<collection provider="#{budgetedProfitAndLossComparison.list}"/>
		<params>
			<param id="REPORT_RESOURCE_BUNDLE" value="com.code.aon.ui.accounting.i18n.report" />
			<param id="company" value="#{company.obtainCompany}" />
			<param id="params" value="#{budgetedProfitAndLossReport.getParameters}" />
		</params>
	</report>

	<!--  LISTADO DETALLADO DE CUENTAS CON PRESUPUESTO -->
	<report id="budgetDetailList" description="BudgetDetailList">
		<template path="/com/code/aon/ui/accounting/report/budgetDetailList.jasper"/>
		<bean key="com.code.aon.accounting.AccountBudgetDetail" />
		<criteria provider="#{accountBudgetDetail}"/>
		<fetch-mode paginated="true" page-count="5000" virtualizer-max-size="1000" />
		<params>
			<param id="REPORT_RESOURCE_BUNDLE" value="com.code.aon.ui.accounting.i18n.report" />
			<param id="company" value="#{company.obtainCompany}" />
			<param id="debitTotal" value="#{accountBudget.getDebitTotal}" />
			<param id="monthNames" value="#{accountBudget.getMonthNames()}" />
		</params>
	</report>
	
	<!--  EXTRACTO DE CUENTA -->
	<report id="statement" description="Account Statement">
		<template path="/com/code/aon/ui/accounting/report/statement.jasper"/>
		<collection provider="#{statement}"/>
		<params>
			<param id="REPORT_RESOURCE_BUNDLE" value="com.code.aon.ui.accounting.i18n.report" />
			<param id="company" value="#{company.obtainCompany}" />
			<param id="openingEntry" value="#{statement.getOpeningEntry}" />
			<param id="fromOpeningEntry" value="#{statement.getFromOpeningEntry}" />
			<param id="periodBalance" value="#{statement.getPeriodBalance}" />
			<param id="params" value="#{trialBalance.getParameters}" />
		</params>
	</report>

	<!--  BALANCE DE SUMAS Y SALDOS -->
	<report id="trialBalance" description="trialBalance">
		<template path="/com/code/aon/ui/accounting/report/trialBalance.jasper"/>
		<collection provider="#{trialBalance}"/>
		<params>
			<param id="REPORT_RESOURCE_BUNDLE" value="com.code.aon.ui.accounting.i18n.report" />
			<param id="company" value="#{company.obtainCompany}" />
			<param id="summaryCollection" value="#{trialBalance.getSummaryCollection}" />
			<param id="params" value="#{trialBalance.getParameters}" />
		</params>
	</report>

	<!--  LISTADO DIARIO DE APUNTES -->
	<report id="journalBook" description="Listado Diario de Apuntes">
		<template path="/com/code/aon/ui/accounting/report/journalBook.jasper"/>
		<bean key="com.code.aon.accounting.AccountEntryDetail" />
		<criteria provider="#{journalReport}"/>
		<fetch-mode paginated="true" page-count="5000" virtualizer-max-size="1000" />
		<params>
			<param id="REPORT_RESOURCE_BUNDLE" value="com.code.aon.ui.accounting.i18n.report" />
			<param id="company" value="#{company.obtainCompany}" />
			<param id="fromDate" value="#{journalReport.getFromDate}" />
			<param id="toDate" value="#{journalReport.getToDate}" />
			<param id="date" value="#{journalReport.getDate}" />
			<param id="period" value="#{journalReport.getPeriod}" />
		</params>
	</report>

</report-config>

=== aonsolutions/aon-application/tags/v_4_3_0_SNAPSHOT/aon-ui-campaign/src/main/resources/META-INF/report-config.xml
<?xml version="1.0" encoding="ISO-8859-1"?>
<!DOCTYPE report-config 
	PUBLIC "-//CODE-AON//DTD Report Config//EN" 
	"http://co-de.com/aon/report-config.dtd">

<report-config>
	<default-config>
		<fetch-mode paginated="false" />
	</default-config>

	<!--  **********************************************************
						      Campaign Monitor
		  ********************************************************** -->
	<report id="campaignMonitorReport" description="Campaign Monitor Report">
		<template path="/com/code/aon/ui/campaign/report/campaignMonitorReport.jasper" />
		<collection provider="#{campaignDossier}"/>
		<params>
			<param id="REPORT_RESOURCE_BUNDLE" value="com.code.aon.ui.campaign.i18n.report" />
			<param id="logoImageFile" value="#{company.getAttachAsInputStream}" />
			<param id="company" value="#{company.obtainCompany}" />
		</params>
	</report>

</report-config>
